server:
  port: 8100
spring:
  application:
    name: eureka-server
  security:
    user:
      name: dzero
      password: dzero
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true  #默认为开启，false关闭保护机制，这样可以确保注册中心中不可用的实例被及时的剔除（不推荐）,生产环境中一定要设为ture
  client:
    fetchRegistry: false #表示自己是注册中心，职责是维护服务，而不是调用服务
    register-with-eureka: false #不向自己注册
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/